apiVersion: 1

datasources:
  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://redis:6379/
  - name: SimpleJson
    type: grafana-simple-json-datasource
    access: proxy
    url: http://leaderboard:5000/
  # - name: Redis
  #   type: redis-datasource
  #   access: proxy
  #   url: ENDPOINT
  #   secureJsonData:
  #     password: PASSWORD