{
 "title": "PoPs and Group Leaderboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "PoP Leaders",
   "type": "table",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "target": "LeaderBoard-Pop", "type": "table" }
   ]
  },
  {
   "title": "Group Leaders",
   "type": "table",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "target": "LeaderBoard-Groups", "type": "table" }
   ]
  },
  {
   "title": "Leading Players",
   "type": "table",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "target": "LeaderBoard-Users", "type": "table" }
   ]
  },
  {
   "title": "Matches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 14 },
   "targets": [
    {
     "aggregation": "count",
     "bucket": 80,
     "command": "ts.range",
     "filter": "matches",
     "keyName": "match",
     "type": "timeSeries"
    }
   ]
  },
  {
   "title": "Total Matches",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "command": "ts.get", "keyName": "match", "type": "timeSeries" }
   ]
  }
 ]
}